#!/usr/bin/env bash

VERSION="v0.2"

actions=('add' 'open' 'edit' 'del' 'version')

buku_cmd="buku --nostdin --tacit --np --nc"

url_regexp='^(http(s)?:\/\/)?(www.)?([a-zA-Z0-9])+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-zA-Z]{2,5}(:[0-9]{1,5})?(\/[^\s]*)?$'

declare -A flags=(
    ["add"]="--add"
    ["open"]="--open"
    ["edit"]="--update"
    ["del"]="--delete"
)

log() {
    echo "message-info '$1'" >>"$QUTE_FIFO"
}

error_log() {
    echo "message-error '$1'" >>"$QUTE_FIFO"
    exit
}

run_buku() {
    # shellcheck disable=SC2068
    if $buku_cmd "${flags["$1"]}" ${@:2}; then
        log "Success"
    else
        error_log "Something wrong happened"
    fi
    exit
}

search() {
    open_count="$1"
    search_flag="$2"
    query="${3//\*/\\*}"

    # shellcheck disable=SC2068
    result_str=$($buku_cmd --format 1 "$search_flag" ${query[@]} | grep -Eo '^[0-9]+' | head -n "$open_count")

    echo "${result_str//\\n/ }"
}

parse_query() {
    query=""
    while [[ "$1" =~ [^-][[:alpha:]]* ]]; do
        query+="$1 "
        shift
    done

    echo "$query"
}

# shellcheck disable=SC2076
if [[ " ${actions[*]} " =~ " $1 " ]]; then
    action="$1"
    shift
else
    action="add"
fi

# Argument Parsing
while : ; do
    case "$1" in
    -n*)
        if [[ "$1" =~ -n[[:digit:]]+ ]]; then
            limit=$( echo "$1" | grep -Eo '[[:digit:]]+' )
            shift
        elif [[ "$1" == "-n" ]] && [[ "$2" =~ [[:digit:]]+ ]]; then
            limit="$2"
            shift 2
        else
            error_log "The -n flag only accepts a number"
        fi
        ;;
    -s)
        search=true
        search_type="--sany"
        search_query=$(parse_query "$@")
        shift "$#"
        ;;
    -S)
        search=true
        search_type="--sall"
        search_query=$(parse_query "$@")
        shift "$#"
        ;;
    *)
        break
        ;;
    esac
done

case $action in
add)
    if echo "$1" | grep -qP "$url_regexp"; then
        run_buku add "$@"
    fi

    run_buku add "$QUTE_URL" "$@"
    ;;
open)
    if [[ -z "$1" ]] && [[ ! $search ]]; then
        error_log "At least 1 argument required: index | query | tag"
    fi

    if [[ -n "$1" ]]; then
        if [[ "$1" =~ ^[[:digit:]]+$ ]] || [[ "$1" =~ ^[[:digit:]]+-[[:digit:]]+$ ]]; then
            index="$1"
        else
            search=true
            search_type="--sany"
            search_query=$(parse_query "$@")
            shift "$#"
        fi
        shift
    fi

    if [[ ! $search ]]; then
        log "OK"
        run_buku open "$index"
    fi

    result=$(search "${limit:-1}" "$search_type" "$search_query")
    run_buku open "${result[@]}"
    ;;
edit)
    if [[ -z "$1" ]]; then
        error_log "argument required: tag"
    fi

    run_buku edit "$@"
    ;;
del)
    if [[ -z "$1" ]]; then
        error_log "argument required: tag | tag range"
    fi

    run_buku del "$@"
    ;;
version)
    log "Buku Version: v$($buku_cmd -v), userscript version: ${VERSION}"
esac
