#!/usr/bin/env bash

userscript_download_url="https://raw.githubusercontent.com/spectronp/qutebrowser-buku/main/buku"
install_dir="$HOME/.local/share/qutebrowser/userscripts/" # TODO -- ask user

if [[ "$1" == "-u" ]] && rm "$install_dir"/buku; then
    echo "Uninstalled Successfully"
    exit
elif [[ "$1" == "-u" ]]; then
    echo "Error while trying to uninstall"
    exit 1
fi

if [[ ! -x buku ]] && [[ ! $(file buku) =~ "Bourne-Again shell script" ]]; then
    # not inside the git repo
    cd /tmp
    wget $userscript_download_url
fi

if install -Dm744 buku "$install_dir"/buku; then
    if [[ "$PWD" == '/tmp' ]]; then
        rm 
    fi
    echo "Installed Successfully"
else
    echo "Error while trying to install"
    exit 1
fi
